### ISSUE TITLE
C_DigestUpdate does not support HMAC mechanisms

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#10]
It seems incorrect that C_DigestUpdate does not support updating hmacs.
If the pkcs#11v2.20 spec does not restrict this, then the code needs to be changed to do this.

This  issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/144/

**Comment by ifranzki** [comment]
Hmm, well HMAC is used for Sign/Verify, not for Digest …. So C_DigestUpdate can not be used with HMAC mechanisms anyway.... 

Common code supports SignUpdate with HMAC, the same is true for the CCA, Soft and EP11 token. The ICA, ICSF and TPM tokens do not support HMAC at all.

Based on this I would say that this issue can be closed.

**Comment by p-steuer** [comment]
I agree DigestUpdate N/A for hmac.
