### ISSUE TITLE
pkcsslotd running like a zombie

### ISSUE THREAD

**Issue by jamesgua** [opencryptoki/opencryptoki#116]
start daemon pkcsslotd as "pkcsslotd start", however, if I check its status or try to stop it, multi processes started:
ps -Al | grep pkcsslotd
1 S     0  2270     1  0  80   0 -   605 poll_s ?        00:00:02 pkcsslotd
1 S     0 10608     1  0  80   0 -   605 poll_s ?        00:00:00 pkcsslotd
1 S     0 22246     1  0  80   0 -   605 poll_s ?        00:00:00 pkcsslotd
1 S     0 23840     1  0  80   0 -   605 poll_s ?        00:00:00 pkcsslotd
1 S     0 32402     1  0  80   0 -   605 poll_s ?        00:00:00 pkcsslotd

dig into you will find actual cmdline is 
cat /proc/2270/cmdline--------------->/usr/sbin/pkcsslotd
cat /proc/10608/cmdline-------------->pkcsslotdstop
cat /proc/22246/cmdline-------------->pkcsslotd-v-l/tmp/pkcsslotd.log

And its pid file updated also:
cat /var/run/pkcsslotd.pid ------------->10608

Even if I am not using it properly, it still should not behave like this, it's confusing and looks dangerous.

**Comment by dodys** [comment]
I can see that you are making calls to the /usr/sbin/pkcsslotd.
This executable doesn't deal with "start" and/or "stop". So if you ran: 
pkcsslotd start 
and then later 
pkcsslotd stop 
You actually did two calls to run pkcsslotd, which will prepare shared memory and other stuff... so what you saw is a "normal" behaviour. 

You apparentely want to use the pkcsslotd service to start and stop the daemon. This service should be used as:
systemctl start pkcsslotd.service 
systemctl stop pkcsslotd.service

Please also read the following if you want to manually run /usr/sbin/pkcsslotd:
 https://github.com/opencryptoki/opencryptoki/blob/master/doc/opencryptoki-howto.md#71-slot-manager-daemon
