### ISSUE TITLE
The rsa_hash_pkcs_* functions in mech_rsa.c should perhaps not call *_mgr_cleanup.

### ISSUE THREAD

**Issue by dodys** [opencryptoki/opencryptoki#13]
The rsa_hash_pkcs_ functions in mech_rsa call _mgr_cleanup. This seems incorrect. And some call it regardless of outcome.
Investigate if this is correct. Because currently SC_Sign and SC_Verify functions in new_host.c also call *_mgr_cleanup function and do it correctlly according to the spec..
"The signing operation must have been initialized with C_SignInit.
A call to C_Sign always terminates the active signing operation unless it
returns CKR_BUFFER_TOO_SMALL or is a successful call (i.e., one which
returns CKR_OK) to determine the length of the buffer needed to hold the
signature."

The rsa_hash_pkcs_* functions perhaps should not call cleanup and leave it to the caller in new_host.c...

This issue may also be in the Encrypt and Decrypt functions to.

This issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/149/

**Comment by ifranzki** [comment]
The same seem to be the case for ec_hash_sign in mech_ec.c

**Comment by ifranzki** [comment]
I checked the code and those calls to _mgr_cleanup are OK.
Those are all **local contexts** that are setup within the function and are cleaned up at the end of the function. The context passed to the function is not cleaned up, but is left to clean up by the caller.

So this is works as designed and the issue can be closed.

**Comment by p-steuer** [comment]
Closing based on ingo's analysis.
