### ISSUE TITLE
Rework 3DES test vectors in testcases/crypto/des3.h

### ISSUE THREAD

**Issue by ifranzki** [opencryptoki/opencryptoki#132]
The 3DES test vectors in des3.h use keys where two or more key parts are equal. These keys are rejected by FIPS-enabled tokens, such as the ICA token, when running with a FIPS enabled libica. 
Because of this, the test vectors were disabled with commit 3e091d7ff34a56eac0b9a5e8eaf92e5a7cf11b7f, leaving only very few valid 3DES testcases.
We should replace the invalid test vectors with others using FIPS compliant keys.

**Comment by p-steuer** [comment]
Fixed by #148 . Closing.
