### ISSUE TITLE
C_Login call should return CKR_OK in following position.

### ISSUE THREAD

**Issue by sahilnxp** [opencryptoki/opencryptoki#145]
https://github.com/opencryptoki/opencryptoki/blob/29b3a2f02f886f5720cf59c62ddac880acb42244/testcases/pkcs11/sess_mgmt.c#L358

Since all the sessions are logged out and we tried logginf in h1 in its previous call which fails, so till now there is no user logged in.
Also this h2 is a R/W session, I think it should return CKR_OK.

Please correct me if I am wrong.
Thanks.

**Comment by ifranzki** [comment]
This is the code in common/new_host.c in function SC_Login that checks the Login and Session states (see below). Please also note the comment at the beginning of this block. 

The reason for the CKR_SESSION_READ_ONLY_EXISTS is the check for session_mgr_readonly_session_exists(). 
I guess the rationale behind this is that there exist no "R/O SO Functions" state. So when trying to log in SO, but there is a R/O session, this would produce an R/O SO session, which can not exist.

The PKCS#11 standard states in the description of the C_Login Function:
> When the user type is either CKU_SO or CKU_USER, if the call succeeds, each of the application's
> sessions will enter either the "R/W SO Functions" state, the "R/W User Functions" state, or the "R/O User
> Functions" state.

So there is no "R/O SO Functions" state.

Also the PKCS#11 standard states the following in the description of return code CKR_SESSION_READ_ONLY_EXISTS in section "5.1.6 All other Cryptoki function return values":
> CKR_SESSION_READ_ONLY_EXISTS: A read-only session already exists, and so the SO cannot
> be logged in.

Based on that, I think that the code is correct.
```
    /* PKCS #11 v2.01 requires that all sessions have the same login status:
     * --> all sessions are public, all are SO or all are USER
     */
    if (userType == CKU_USER) {
        if (session_mgr_so_session_exists()) {
            TRACE_ERROR("%s\n", ock_err(ERR_USER_ANOTHER_ALREADY_LOGGED_IN));
            rc = CKR_USER_ANOTHER_ALREADY_LOGGED_IN;
        }
        if (session_mgr_user_session_exists()) {
            TRACE_ERROR("%s\n", ock_err(ERR_USER_ALREADY_LOGGED_IN));
            rc = CKR_USER_ALREADY_LOGGED_IN;
        }
    } else if (userType == CKU_SO) {
        if (session_mgr_user_session_exists()) {
            TRACE_ERROR("%s\n", ock_err(ERR_USER_ANOTHER_ALREADY_LOGGED_IN));
            rc = CKR_USER_ANOTHER_ALREADY_LOGGED_IN;
        }
        if (session_mgr_so_session_exists()) {
            TRACE_ERROR("%s\n", ock_err(ERR_USER_ALREADY_LOGGED_IN));
            rc = CKR_USER_ALREADY_LOGGED_IN;
        }
        if (session_mgr_readonly_session_exists()) {
            TRACE_ERROR("%s\n", ock_err(ERR_SESSION_READ_ONLY_EXISTS));
            rc = CKR_SESSION_READ_ONLY_EXISTS;
        }
    } else {
        rc = CKR_USER_TYPE_INVALID;
        TRACE_ERROR("%s\n", ock_err(ERR_USER_TYPE_INVALID));
    }

```

**Comment by sahilnxp** [comment]
Thanks @ifranzki for reply.
But In this case we are trying to login to session 'h2' which is R/W Session and SO can login to R/W session.

Please check.
