### ISSUE TITLE
documentation findings coming with source

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#15]
Internal driver with opencryptoki V3.2 installed. Checking some of the documentation coming with the rpms I found following:

1) README-IBM_CCA_users

>  a) talk about pkcsconf64 this is in V3 and higher no longer available. You only use pkcsconf
>  b) a device driver zsecrypt does not exist anymore since long time.
>  c) source package xcryptolinz (cca v3.28) is real old and does not support newer cards like CEX3C, CEX4C and CEX5C. For this the new CCA rpm is called  "csulcca...."
>  d) pk_config_data is no longer used in opencryptoki V3
>  e) description for new behavior (at least the part needed for CCA token) of opencryptoki V3 is totally missing

2) README

>  a) you talk about opencryptoki V3.2 but directly in the overview you show V3.1
>  b) Requirements:  IBM CCA      you should state CEX3C or higher and you need CCA host lib installed by CCA rpm (csulcca....rpm)
>                                    IBM EP11    you should state CEX4P or higher and you need EP11 host lib installed by EP11 rpms (2 pieces)
>   c) you show token objects but not all so i miss the objects for CCA and EP11 token
>   d) the web link under Configuration is broken and does not exist (http://www-128.ibm.com/developerworks/security/library/s-pkcs/index.html)

3) opencryptoki-HOWTO.pdf (comments for opencryptoki V3 and higher)

>    a) This document is in parts outdated for opencryptoki V3
>    b) chap. 5.2 i think opencryptoki is now hosted in sourceforge. web link is broken
>    c) chap. 6.1 configuration changed now complete no longer usage of pkcs11:startup
>    d) chap. 6.2 no longer used is pk_config_data, behavior changed in storing infos, keys
>    e) chap. 6.3 pkcs11_startup  no longer used
>     f) chap. 7.1 pk_config_data no longer used
>     g) chap. 7.3 nothing said about the ICA, SW, CCA and EP11 tokens
>     h) chap. 9 at least on link broken

No description about the new way of configuration and storing information

This issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/159/

**Comment by dodys** [comment]
Fixed with the merge of pull request #55
