### ISSUE TITLE
C_DigestKey broken in CCA token

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#16]
The function C_DigestKey does not work for the CCA token.

It hashes the value of the CKA_VALUE attribute which is meaningless for a secure key.

Given that there is no easy fix to the problem (I am not even sure whether the CCA library supoorts hashing a secure key.) the C_DigestKey function should return CKR_FUNCTION_NOT_SUPPORTED when called for the CCA token.

**Comment by ifranzki** [comment]
Same is true for the EP11 token.

**Comment by p-steuer** [comment]
Fixed with https://github.com/opencryptoki/opencryptoki/commit/776943fe229df76b773fbbf878e4ff60cb550122 . Closing.
