### ISSUE TITLE
Building opencryptoki with openssl 1.1.0h

### ISSUE THREAD

**Issue by johughes99** [opencryptoki/opencryptoki#163]
I'm trying to build opencryptoki on Ubuntu 16.0.4 LTS.  ./bootstrap and ./configure work fine - but I get multiple errors with make. As I only want to use the soft token I use:

   ./configure --enable-swtok --disable-ccatok -- disable-icsftok

However, near the end of make I get lots of errors such as:

/usr/lib/pkcs11/soft_stdll/soft_specific.c:1873: undefined reference to `DH_set0_pqg'
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:1891: undefined reference to `DH_get0_key'
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:1912: undefined reference to `DH_get0_key'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac_update':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2601: undefined reference to `EVP_MD_CTX_free'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2558: undefined reference to `EVP_MD_CTX_free'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac_final':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2702: undefined reference to `EVP_MD_CTX_free'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac_init':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2407: undefined reference to `EVP_MD_CTX_new'
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2441: undefined reference to `EVP_MD_CTX_free'

I'm just wondering where there is a problem in building opencryptoki with openssl 1.1.0h

**Comment by p-steuer** [comment]
As far as i know ubuntu 16.04 comes with openssl 1.0.2. Do you have multiple openssl versions installed ? The errors look like opencryptoki was build including openssl 1.1.0 header files but tries to link with a 1.0.2 libcrypto .

**Comment by johughes99** [comment]
Following a touch more research - its seems that 1.1.0h is installed in /usr/local/lib whilst 1.0.0 is in /usr/lib/x86_64-linux-gnu (and /lib/x86_64-linux-gnu).  So it looks like the configure/make process is picking up the x86_64-linux-gnu version for the libraries.

**Comment by johughes99** [comment]
I set the env variables as stated above - but still get the same errors (see below as an example)

: In function `token_specific_dh_pkcs_key_pair_gen':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:1873: undefined reference to `DH_set0_pqg'
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:1891: undefined reference to `DH_get0_key'
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:1912: undefined reference to `DH_get0_key'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac_update':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2601: undefined reference to `EVP_MD_CTX_free'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2558: undefined reference to `EVP_MD_CTX_free'
.libs/opencryptoki_stdll_libpkcs11_sw_la-soft_specific.o: In function `softtok_hmac_final':
/home/johughes/Downloads/opencryptoki-master/usr/lib/pkcs11/soft_stdll/soft_specific.c:2702: undefined reference to `EVP_MD_CTX_free'

**Comment by p-steuer** [comment]
Can you provide the full build log ?
```
Please use thè ``` [...] ``` markdown environment.
```
Can you also provide the output of the following commands:
```
find / -name "libcrypto.*"
find / -name "dh\.h"
printenv | grep LD_LIBRARY_PATH
printenv | grep LD_RUN_PATH
```

**Comment by p-steuer** [comment]
okay, so openssl 1.1.0 is found at runtime (see openssl version -a output), so LD_LIBRARY_PATH is searched.

However, the error is at link time, ie the LD_RUN_PATH setting is somehow being ignored.

Do a 'make clean' and run configure with the additional option  '--with-openssl=/usr/local/lib/'. This should resolve the link time error.

**Comment by johughes99** [comment]
Whilst looking at the code I noticed that comment said that LD_LIBRARY_PATH had to be set for the location of the .so do I changed it now to  /usr/local/lib/pkcs11 (as opposed to what was used during the build).

However, when try to do pkcsconf -i I get:
Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)


And the source in pkcsconf.c indicates perhaps a slot manager needs to be executing.

**Comment by p-steuer** [comment]
So i read from your comment, that you already solved this error
> Error loading PKCS#11 library
dlopen error: libopencryptoki.so: cannot open shared object file: No such file or directory

by setting LD_LIBRARY_PATH and the error you get now is
> Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)

Did you add the user to the pkcs11 group ?
Did you successfully start the daemon (pkcsslotd) before running pkcsconf ?

**Comment by johughes99** [comment]
So I set LD_LIBRARY_PATH to be /usr/local/lib/pkcs11 and indeed pkcsconf loaded the module ok.  However, when I either did pkcsconf -i or tried my test program I got back CKR_FUNCTION_FAILED.  I successfully started pkcslotd using sudo prior to that - or at least no errors were reported on the console.
 The error return seems to come from the c_initialize call.

Note that I have tried to set LD_RUN_PATH to various settings - including /usr/local/lib/pkcs11 without any success.

**Comment by johughes99** [comment]
Just an update.  I rebooted my VM.  I then:
- set LD_LIBRARY_PATH to be /usr/local/lib/pkcs11
- ran pkcsslotd
- and then typed pkcsconf -i

then I got:
C_GetSlotList returned 0 slots. Check that your tokens are installed correctly.

So it looks like its very nearly working - and just cant find the .so sw token.  Is this where LD_RUN_PATH should be set up to point at?

**Comment by johughes99** [comment]
Syslog has this in it:

Sep 11 00:53:40 Cicada pkcs11_compat: apiutil.c DL_Load: dlopen() failed for [libpkcs11_tpm.so]; dlerror = [libpkcs11_tpm.so: cannot open shared object file: No such file or directory]
Sep 11 00:53:40 Cicada pkcs11_compat: apiutil.c DL_Load: dlopen() failed for [libpkcs11_ica.so]; dlerror = [libpkcs11_ica.so: cannot open shared object file: No such file or directory]
Sep 11 00:53:40 Cicada pkcs11_compat: apiutil.c DL_Load: dlopen() failed for [libpkcs11_cca.so]; dlerror = [libpkcs11_cca.so: cannot open shared object file: No such file or directory]
Sep 11 00:53:40 Cicada pkcs11_compat: apiutil.c DL_Load: dlopen() failed for [libpkcs11_sw.so]; dlerror = [libpkcs11_sw.so: cannot open shared object file: No such file or directory]
Sep 11 00:53:40 Cicada pkcs11_compat: apiutil.c DL_Load: dlopen() failed for [libpkcs11_ep11.so]; dlerror = [libpkcs11_ep11.so: cannot open shared object file: No such file or directory]

ls -l /usr/local/lib/opencryptoki/stdll/ gives
total 2264
-rwxr-xr-x 1 root root    1038 Sep  8 02:47 libpkcs11_sw.la
lrwxrwxrwx 1 root root      21 Sep  8 02:47 libpkcs11_sw.so -> libpkcs11_sw.so.0.0.0
lrwxrwxrwx 1 root root      21 Sep  8 02:47 libpkcs11_sw.so.0 -> libpkcs11_sw.so.0.0.0
-rwxr-xr-x 1 root root 2313576 Sep  8 02:47 libpkcs11_sw.so.0.0.0
lrwxrwxrwx 1 root root      15 Sep  8 02:47 PKCS11_SW.so -> libpkcs11_sw.so

and the opencryptoki.conf contains:

slot 3
{
stdll = libpkcs11_sw.so
}

it just looks like it cant find the token file.  

I will do the debug output in a minute.

**Comment by johughes99** [comment]
The trace file just shows:

09/11/2018 01:02:51 [api_interface.c:2512 api] INFO: C_Initialize
09/11/2018 01:02:51 [api_interface.c:2305 api] INFO: C_GetSlotList
09/11/2018 01:02:51 [api_interface.c:1282 api] INFO: C_Finalize
09/11/2018 01:02:51 [api_interface.c:111 api] INFO: CloseAllSessions
09/11/2018 01:02:51 [api_interface.c:111 api] INFO: CloseAllSessions
09/11/2018 01:02:51 [api_interface.c:111 api] INFO: CloseAllSessions
09/11/2018 01:02:51 [api_interface.c:111 api] INFO: CloseAllSessions
09/11/2018 01:02:51 [api_interface.c:111 api] INFO: CloseAllSessions

**Comment by hfreude** [comment]
Hello

with 'make install' opencryptoki installs a file /etc/ld.so.conf.d/opencryptoki-x84_64.conf.
You need to activate this file with 'sudo ldconf' once, so that the 2 directories where
opencryptoki and token shared libs are located are known to your system.
After this, your pkcsconf -i should not fail anymore and show at least the soft token.

regards, H.Freudenberger

**Comment by johughes99** [comment]
I checked that I had opencryptoki-x86_64.conf installed and I do.  The file contains:

/usr/local/lib/opencryptoki
/usr/local/lib/opencryptoki/stdll

However, "sudo ldconf" says it cant find the command.

Just to check on this I added those two directories into $PATH - and still get the C_GetSlotList returned 0 slots error (having killed pkcsslotd and restarted it)

**Comment by p-steuer** [comment]
It was a typo by harald, the correct command is:
```
sudo ldconfig
```

**Comment by johughes99** [comment]
I wondered that - but wasn't sure what he meant!

Any way it WORKS.  So many thanks guys for helping me out on this.

John

**Comment by p-steuer** [comment]
Your welcome : -)

Closing.
