### ISSUE TITLE
Return useful information for ulRwSessionCount with C_GetTokenInfo

### ISSUE THREAD

**Issue by dodys** [opencryptoki/opencryptoki#17]
The token info is initialized in init_tokenInfo, and most of this info is saved in nv_tok_data.But for C_GetTokenInfo we call copy_token_contents_sensibly() and we do not copy over all the info in nv_tok_data. For example, ulMaxSessionCount, ulMaxRwSessionCount, ulTotalPublicMemory. 
Investigate why.

This issue was migrated from: https://sourceforge.net/p/opencryptoki/bugs/158/

**Comment by ifranzki** [comment]
ulTotalPublicMemory is copied over in the current code.

ulMaxSessionCount and ulMaxRwSessionCount are both returned as ULONG_MAX - 1.
Function init_tokenInfo() initializes those with CK_UNAVAILABLE_INFORMATION, like most of the values.
So copy_token_contents_sensibly() at least returns somewhat more useful information.

Most of these values are never updated during runtime anyway, so they do not return any really useful information.  ulSessionCount is updated in api_interface.c's C_GetTokenInfo().

The only thing to add would be to return a correct ulRwSessionCount.

**Comment by p-steuer** [comment]
Not sure about this one. Do we plan to do something here or can it be closed ?

**Comment by ifranzki** [comment]
I think the code is OK as is.
We might want to look into returning useful numbers in ulRwSessionCount at some point in time, but I don't see this as urgent. Maybe we open a new feature-type issue for this.

**Comment by p-steuer** [comment]
I already re-labeled it from bug to improvement. So ill leave that one open.
