### ISSUE TITLE
NUMBER_SLOTS_MANAGED vs MAX_SLOT_ID

### ISSUE THREAD

**Issue by p-steuer** [opencryptoki/opencryptoki#171]
MAX_SLOT_ID and NUMBER_SLOTS_MANAGED are defined as 1024. However, slot numbers are checked for <= MAX_SLOT_ID in some places and <  NUMBER_SLOTS_MANAGED in others.

**Comment by ifranzki** [comment]
MAX_SLOT_ID should be 1023. It is only used in the tokens (new_host.c) to validate the slot ID passed.  The rest of the common code (mainly api_interface.c) uses NUMBER_SLOTS_MANAGED and compares >= plus allocates arrays of 1024 elements (index 0 - 1023). Thus I would assume that the token never gets a slot ID larger than 1023 anyway, but lets correct it.

**Comment by p-steuer** [comment]
Fixed by dba6d50c752d27d8e08792d37d2dc879528d50ad .
