### ISSUE TITLE
Investigate cryptokiVersion returned by C_GetInfo

### ISSUE THREAD

**Issue by ifranzki** [opencryptoki/opencryptoki#177]
Function C_GetInfo returns information in struct CK_INFO, including the library version but also the cryptoki version. This information can be displayed using `pkcsconf -i`

The cryptoki version is set from defines CRYPTOKI_API_MAJOR_V (=2) and CRYPTOKI_API_MINOR_V (=20) defined in slotmgr.h. Not sure if this needs to be updated. The PKCS#11 standard defines this as:

> Cryptoki interface version number, for compatibility with future revisions of this interface

Not sure if this is supposed to specify the PKCS#11 version that OCK is supporting? If so, then we probably need to update this to 2.40?

The library version is determined from define PACKAGE_VERSION which is set in the make file. PACKAGE_VERSION is updated with each new OCK version.  There are also defines LIB_MAJOR_V (=1) and LIB_MINOR_V (=4) but this information is then overridden when PACKAGE_VERSION is defined. So the library version is OK.

**Comment by p-steuer** [comment]
ock implements the cryptoki 2.20 api but has some 2.40 features. Until we evaluated the 2.2.0 vs 2.40 diff, its better to claim 2.2.0.

**Comment by ifranzki** [comment]
Agreed, but do we know where we currently do not comply with v2.40 ?

**Comment by p-steuer** [comment]
we dont know. though its unlikely to comply with something by chance.

**Comment by p-steuer** [comment]
opencryptoki.spec sample says 2.20

**Comment by p-steuer** [comment]
Can this one be closed ? Id say we dont change it until we are sure we actually comply with something > 2.20. I expect this to be the case when we are done with the planned 3.0 work ..

**Comment by ifranzki** [comment]
Yes I agree, lets close it.
