### ISSUE TITLE
Add support for dynamic adapter hotplug events

### ISSUE THREAD

**Issue by ifranzki** [opencryptoki/opencryptoki#191]
A token may be backed by one or multiple crypto adapters. This is the case for the EP11 token, but may also be the case for the CCA token.
Crypto adapters are **hot pluggable**, that is, crypto adapters may come and go during runtime.
Some token functions require to know the list of adapters that are currently online for the token.

Add a framework into OCK common code that allows a token to receive events when a crypto adapter becomes online or offline, or other crypto adapter triggered events.

This could work as follows (basic idea only, needs more design work):
- udev notifies the pkcsslotd about an event, either via sending a signal to it, or via a unix socket connection.
- pkcsslotd notifies all active tokens (i.e. user processes). This could be done via a unix socket connection between the token in the user process and the pkcsslotd. The unix connection is established by the token in a new event-thread that is attached during token initialization (common code). 
- A token registers an event-callback routine with common code. When an event is received byte the event-thread, the callback function is called inside the token to let the token code handle the event. 
- The  event must contain a unique identification of the adapter (i.e. card & domain), so that the token can decide if the adapter is of interest for it or not.

A similar function is requires in order to support **concurrent master key changes**. This would allow a token to receive an event that the master key of a crypto adapter has changed or is being changed. The token could then re-encipher its session key-objects, as well as the token key-objects (attention: multiple user processes may be using the same token concurrently, thus sharing the token objects).

PKCS#11 supports **slot events**,  e.g. Token insertion/removal can be queried by C_WaitForSlotEvent. C_GetSlotInfo would return a CK_SLOT_INFO in that case with the CKF_TOKEN_PRESENT flag off. Investigate if this can be used to support above, or if this is on a different level. As of today OCK implements C_WaitForSlotEvent very roughly. I am not sure if slots can be added/removed dynamically at all with the current implementation. This may also be related to issue https://github.com/opencryptoki/opencryptoki/issues/28

**Comment by ifranzki** [comment]
Actually C_WaitForSlotEvent will currently always return CKR_FUNCTION_NOT_SUPPORTED, since the event handling code is masked out via #ifdef PLUGGABLE_TOKENS_SUPPORTED.

**Comment by p-steuer** [comment]
yes that is what i wanted to point out: pkcs11 supports event handling, we just havent implemented it yet.

**Comment by ifranzki** [comment]
Yes it does, but the type of event handling might not be what we need. The PCKS#11-type of event handling seems to be to notify the user application about events. We need a way to notify the tokens about events (caused by crypto adapters). Those events will not be seen by the user application at all. Instead these events will be OCK and token internally.

**Comment by ifranzki** [comment]
Event support is now available on top of 3.16.0, including UDEV events for crypto adapter.
