### ISSUE TITLE
TPM token fails to reinitialize properly on reload

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#2]
From https://bugs.launchpad.net/ubuntu/+source/opencryptoki/+bug/645576

The TPM token code uses some global variables to track the storage root key, root public & private keys, and leaf public & private keys from the TPM. These variables are not properly reinitialized during unload and reload of the module. In the case of wpasupplicant, this results in PKCS#11 becoming unusable and one must kill the process to start a fresh reconfiguration.

Attached (https://sourceforge.net/p/opencryptoki/bugs/_discuss/thread/43d5f504/85d5/attachment/05-reset-tpm-structures.patch) is a patch that cleans up the use of these variables in the token_specific_init() function called when the module is dlopen()'d.

This issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/44/

**Comment by pvital** [comment]
Also worked in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603104 

The mentioned patch has been applied since opencryptoki-2.3.1+dfsg-2 for Debian/Ubuntu.

**Comment by dodys** [comment]
@pvital is this patch still being shipped on opencryptoki deb package? The code changed a lot and I don't think it fits anymore.

**Comment by pvital** [comment]
The patch is not shipped since the time I've got the maintainership of the package in Debian community, but I'm going to take a look better and see if it's necessary, and when and why the patch was removed from the package.

**Comment by pvital** [comment]
My mistake. The patch was renamed in the patch series used to build Debian package and it is still applied to the latest version. I'm going to apply it upstream and create a PR.
