### ISSUE TITLE
weird code in key_mgr.c

### ISSUE THREAD

**Issue by hfreude** [opencryptoki/opencryptoki#202]
There is some strange code in key_mgr.c in the functions key_mgr_generate_key() and key_mgr_generate_key_pair():

    ....
    // we can now set CKA_ALWAYS_SENSITIVE and CKA_NEVER_EXTRACTABLE
    // to their appropriate values.  this only applies to CKO_SECRET_KEY
    // and CKO_PRIVATE_KEY objects
    flag = template_attribute_find(key_obj->template, CKA_SENSITIVE, &attr);
    if (flag == TRUE) {
        flag = *(CK_BBOOL *) attr->pValue;
        rc = build_attribute(CKA_ALWAYS_SENSITIVE, &flag, sizeof(CK_BBOOL),
                             &new_attr);
        if (rc != CKR_OK) {
            TRACE_DEVEL("build attribute failed.\n");
            goto error;
        }
        template_update_attribute(key_obj->template, new_attr);
    } else {
        rc = CKR_FUNCTION_FAILED;
        TRACE_ERROR("Failed to find CKA_SENSITIVE in key object template.\n");
        goto error;
    }

1) the comment can't be true as there is no checking done for any kind of key. Here unconditional the attribute CKA_SENSITIVE is processed. So either remove the comment or improve the code to check for key type.
2) The code which is adding/replacing the CKA_SENSITIVE attribute uses the value which is the extract from the existing CKA_SENSITIVE. So it just replaces the very same attribute with the very same value. This does not make any sence, so either remove this code or what I think was intended is to set the value to TRUE.

**Comment by ifranzki** [comment]
No, you did not get that right. It took me a few looks until I understood it, too :-)
 It checks if CKA_SENSITIVE is set, and if so, then it sets CAK_**ALWAY**_SENSITIVE to the same value as the CKA_SENSITIVE attribute.
So the code makes sense, but the comment above is not 100% true.

**Comment by p-steuer** [comment]
So this one looks like a candidate for closing. Do we want to do something here (change the omment?) or leave it like that ?

**Comment by hfreude** [comment]
Fine with that. Let's close it
