### ISSUE TITLE
Use CSNDPKX in CCA token for RSA/ECC key pairs

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#22]
In the CCA token, when generating RSA key pair, we call CSNDPKB to build the key token and then we call CSNDPKG to generate the key. We get back a byte array that contains the public key and the encrypted private key. We then build CKA_IBM_OPAQUE with the byte array in both the public and private key obects. 

After calling CSNDPKG, we should ideally call next, CSNDPKX to separate the private key and public key info we received from CCA. And then store **ONLY** the public key info. More investigation as to whether to store it in CKA_IBM_OPAQUE or another vendor defined attribute.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/153/

**Comment by ifranzki** [comment]
Fixed with https://github.com/opencryptoki/opencryptoki/commit/3c48f1553468b81e6211ae49beee250a37c8abee
