### ISSUE TITLE
CCA does not support key wrapping with CKM_RSA_PKCS

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#24]
CKM_RSA_PKCS mechanism does not have flags indicating it can do key wrapping for CKM_RSA_PKCS. Investigate why and add support if possible.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/137/

**Comment by ifranzki** [comment]
This is now available with: https://github.com/opencryptoki/opencryptoki/commit/a94b3f13547e8caa92e55fc48523890f1cd70739
