### ISSUE TITLE
Change unversioned dlopen of libep11.so to libep11.so.x

### ISSUE THREAD

**Issue by frank-uhlig** [opencryptoki/opencryptoki#243]
opencryptoki currently opens the libep11 shared object without specifying the version of the library. This will cause problems when the API changes, which will not be reflected in the unversioned shared object.

**Comment by ifranzki** [comment]
We should probably make the name of the shared object configurable in the EP11 token config file (but have a good default that works in most cases). That way we don't always have to change the code when a new ep11lib version comes out.

**Comment by p-steuer** [comment]
I think we would only encode the major version (libep11.so.<major>) which by definition only changes on abi breaks. So hard-coding it would serve as a documentation which abi is needed by ep11tok.

**Comment by ifranzki** [comment]
There is already code to query the EP11 library version, so theoretically we could handle different versions. As long as the ABI break is only the type of the mechanism parameter struct, and not additional parameters of a function, we could handle different EP11 library versions.
