### ISSUE TITLE
ICSF token fails to initialize

### ISSUE THREAD

**Issue by p-steuer** [opencryptoki/opencryptoki#282]
```
# pkcsslotd -t
Token #5 Info:
    Label: OPENCRYPTOKI.1                  
    Manufacturer: ICSF PKCS11 token browser       
    Model: HCR77D0FTok     
    Serial Number: 023             
    Flags: 0x880045 (RNG|LOGIN_REQUIRED|CLOCK_ON_TOKEN|USER_PIN_TO_BE_CHANGED|SO_PIN_TO_BE_CHANGED)
    Sessions: 0/18446744073709551614
    R/W Sessions: 18446744073709551615/18446744073709551614
    PIN Length: 4-8
    Public Memory: 0xFFFFFFFFFFFFFFFF/0xFFFFFFFFFFFFFFFF
    Private Memory: 0xFFFFFFFFFFFFFFFF/0xFFFFFFFFFFFFFFFF
    Hardware Version: 1.0
    Firmware Version: 1.0
    Time: 2020030321310200
 
# pkcsconf -I -c 5
Enter the SO PIN:
Enter a unique token label: myfirsticsftok
Incorrect PIN Entered.

```

**Comment by p-steuer** [comment]
Turned out the "incorrect PIN" error is misleading: The default pin is actually accepted, but afterwards an aes-cbc decryption fails (incorrect padding) when the master key ist loaded. Moreover, there are bugs due to missing blank padding / \0 termination of some strings which lead to wrong pathnames being searched etc. TODO: find the last OCK version with a wroking icsf tok.

**Comment by ifranzki** [comment]
Will be fixed with https://github.com/opencryptoki/opencryptoki/pull/283

This is broken since https://github.com/opencryptoki/opencryptoki/commit/decdf6b8bffba412cacfb9d99dd664b3c089d55c "Pad manufacturerID and slotDescription fields correctly" which
corrected the label field in CK_TOKEN_INFO to be blank padded.

**Comment by p-steuer** [comment]
#283 got merged, so i consider this fixed.
