### ISSUE TITLE
routines in obj_mgr.c have overlapping code

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#29]
For example, object_mgr_add() has much of the exact same code as object_mgr_create_skel() and object_mgr_create_final().

It seems that object_mgr_add() could perhaps call object_mgr_create_skel() and object_mgr_create_final() to eliminate redundant code.

This file should be examined to reduce redundant code.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/113/

**Comment by ifranzki** [comment]
This one has been fixed with https://github.com/opencryptoki/opencryptoki/commit/275f5e55ebb36a946bb787acb37726dc9d6e3e69
