### ISSUE TITLE
our qa test breaks with 3.14 release

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#298]
@p-steuer
Hi, Patrick,
with the change in commit 5d3d1e03e99b663c977b5f94b2fbd7b1c98168ef our QA test does not work anymore because the model was changed from "IBM SoftTok" to "Soft". This information is used in our QA test.
Is the change intended and necessary?
Thanks a lot!

**Comment by p-steuer** [comment]
The commit implements an uniform naming scheme for all the tokens' information (manufacturer, model, description and default label) including soft token.

So the change is intended. However, it is not necessary in the sense that something would break if you used the old names.

**Comment by ngothan** [comment]
Thank you so much for your explanation, we will correct our qa test.
