### ISSUE TITLE
Test case issues summary: Wrong test counting, wrong elapsed time

### ISSUE THREAD

**Issue by chrisRund** [opencryptoki/opencryptoki#311]
The number of Total, Ran, Passed, and Skipped tests appear inconsistent. Adding the sum of skipped to passed is != 'Ran', assuming the Number of (1) Total == Ran + Errors, and
(2) Passed + Failed + Skipped = Ran

In our sample for IBM z15 with an IBM crypto accelerator card backed ICA token we saw the following result line for a completed 'ec_tests' run:
Total=4874, Ran=4673, Passed=4661, Failed=0, Skipped=201, Errors=0 (total elapsed time ...

Thus calculating the total number (1) would result in 4673 Total tests
(2) would result in 4661 + 0 + 201 = 4862 Ran tests

______________________________________________________________________________

In addition the destroyobjects test from the pkcs11 dir passes three tests but counts 0 in 'Total'

Please investigate.
Thanks.

**Comment by jschmidb** [comment]
Hi Christian, I saw that Ingo makes some fixes in ec_func.c with pull request https://github.com/opencryptoki/opencryptoki/pull/310. I will check if this probably affects this issue.

**Comment by ifranzki** [comment]
according to the code in regress.h:   total = ran + skipped

**Comment by ifranzki** [comment]
And ran is only increased when testcase_new_assertion() is used.  I guess that it is not always used where it should be.

**Comment by ifranzki** [comment]
I also noticed that testsuite_skip(n, ...)  (note that this is testsuite, not testcase!) is sometimes called with an invalid 'n' value (e.g. n=1 instead of the number of testcases in the suite). This may cause that the number of skipped testcases is wrong.

**Comment by ifranzki** [comment]
While we are at it: We should aslo make sure that the testcases return a proper exit code (0, of all tests are OK, or != 0 if one or more tests have failed or has errors).

Currently the testcases do this:

```
    ...

    rv = run_DeriveECDHKey();

    rv = run_DeriveECDHKeyKAT();

    testcase_print_result();

    funcs->C_Finalize(NULL);

    /* make sure we return non-zero if rv is non-zero */
    return ((rv == 0) || (rv % 256) ? (int)rv : -1);
}
```
Thats fine if run_DeriveECDHKeyKAT returns a non zero rv, but if any of those above return an non-zero rv, but run_DeriveECDHKeyKAT return 0, then the exit code would not indicate any errors. Also why 'rv % 256' ? 

Maybe it would be better to check global variables t_failed and t_errors and return 0 only if both are zero.

**Comment by jschmidb** [comment]
Yes, definitely!

**Comment by chrisRund** [comment]
Further items encountered during openCryptoki test runs:
The counting of the destroy_objects test and obj_lock tests should also be improved:
         "Total=0, Ran=0, Passed=3, Failed=0, Skipped=0, Errors=0"
obj_lock Test:
        "Total=7, Ran=7, Passed=37, Failed=0, Skipped=0, Errors=0 (total elapsed time 9s 476480us)",

The sess_opstate test does show a too-large elapsed time ( ~50 years )
sess_opstate_funcs PASS (elapsed time 1612461034s 667773us) Get/SetOperationState digest test

**Comment by ifranzki** [comment]
destroy_objects and obj_lock have been fixed in the meantime.

**Comment by ifranzki** [comment]
sess_opstate is also already fixed.
