### ISSUE TITLE
Problem building swtok

### ISSUE THREAD

**Issue by johughes99** [opencryptoki/opencryptoki#319]
I'm trying to build a sw token version.  

Using the following command for configure

` ./configure --disable-icatok --disable-ccatok --disable-ep11tok --enable-swtok --disable-tpmtok --disable-icsftok`

But during the configure process I'm getting the error

`configure: error: lber.h and ldap.h are missing. Please install
			      'openldap-devel'.`

I didn't think I needed openldap if just using the swtok

In any case when I try and do 

`sudo apt-get install openldap-devel`

On Ubuntu it cant find this package

**Comment by johughes99** [comment]
Ok i sorted that out - in Ubuntu you need to install libldap2-dev.  Although not sure why the sw token needs that.

The installation when fine - but when i went to do pkcsconf -i  i got the error:

`Errorloading PKCS#11 library
dlopen error: libopencryptoki.so: cannot open shared object file: No such file or directory`

However, it is installed in /usr/local/lib/opencryptoki - which should be in the search rules

To make sure I added that directory into the PATH env - but still get the same error

**Comment by johughes99** [comment]
Ah - I forgot to look at my notes when I did this some time ago and forgot to do

export LD_LIBRARY_PATH=/usr/local/lib/pkcs11
export LD_RUN_PATH=/usr/local/etc/opencryptoki

Which I don't believe is documented any way

However, if I try any of the sensible pkcsconf commands I get



`Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)
`

Using my test harness I suspect the error is coming from  C_Initialize - and implies the installation failed somehow

**Comment by ifranzki** [comment]
If you install to /usr/local, then you must update LD_LIBRARY_PATH to include /usr/local/lib/, /usr/local/lib/opencryptoki/, and /usr/local/lib/pkcs11/. I.e. here is what I do:
`export LD_LIBRARY_PATH=/usr/local/lib/:/usr/local/lib/opencryptoki/:/usr/local/lib/pkcs11/:/usr/lib64/`
I usually don't update LD_RUN_PATH. 

The `Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)` might be because you started the pkcsslotd before you exported LD_LIBRARY_PATH, so it used the standard libraries from /usr/lib64, and not those you just built. Stop/kill pkcsslotd, and restart it and this error should be gone.

**Comment by johughes99** [comment]
Yup that seemed to partially sort it out - in that Im not getting CKR_FUNCTION_FAILED.

However, I'm not sure how I set up the sw token. If I try to get info:

`pkcsconf -i
C_GetSlotList returned 0 slots. Check that your tokens are installed correctly.`

or initialize the sw token I get

`pkcsconf -I -c 3
C_GetSlotList returned 0 slots. Check that your tokens are installed correctly.
`

I checked that opencryptoki.conf was installed - and it has slot 3 as the sw token.  Containing:

`slot 3
{
stdll = libpkcs11_sw.so
}`

Is there anything else I need to do?

**Comment by ifranzki** [comment]
When installed in `/usr/local`, it also reads the configuration files from `/usr/local/etc/opencryptoki/`. So make sure you adjust that one, not the one in `/etc/opencryptoki`.
Is there anything related in the syslog?
Also, it might help to turn on tracing via `export OPENCRYPTOKI_TRACE_LEVEL=4` and check the trace log in `/usr/local/var/log/opencryptoki/trace.<pid>`

**Comment by johughes99** [comment]
That's the one i looked it.

 When turning on logging I see the following:

`10/12/2020 13:01:22 2879 [usr/lib/api/api_interface.c:2541 api] INFO: C_Initialize
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:392 api] DEVEL: API_Register MgrProcIndc 2879  pid 0 
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_tpm.so failed, dlerror: libpkcs11_tpm.so: cannot open shared object file: No such file or directory
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_ica.so failed, dlerror: libpkcs11_ica.so: cannot open shared object file: No such file or directory
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_cca.so failed, dlerror: libpkcs11_cca.so: cannot open shared object file: No such file or directory
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_sw.so failed, dlerror: libpkcs11_sw.so: cannot open shared object file: No such file or directory
10/12/2020 13:01:22 2879 [usr/lib/api/apiutil.c:518 api] DEVEL: DL_Load of libpkcs11_ep11.so failed, dlerror: libpkcs11_ep11.so: cannot open shared object file: No such file or directory
10/12/2020 13:01:22 2879 [usr/lib/api/api_interface.c:2327 api] INFO: C_GetSlotList
10/12/2020 13:01:22 2879 [usr/lib/api/api_interface.c:2340 api] DEVEL:  Present 1 Count 0
10/12/2020 13:01:22 2879 [usr/lib/api/api_interface.c:1317 api] INFO: C_Finalize
`
And just to check the .so is where it is suiiposed to be:

`johughes@ubuntu:/usr/local/lib/opencryptoki$ ls -l
total 392
-rwxr-xr-x 1 root root   1016 Oct  8 19:58 libopencryptoki.la
lrwxrwxrwx 1 root root     24 Oct  8 19:58 libopencryptoki.so -> libopencryptoki.so.0.0.0
lrwxrwxrwx 1 root root     24 Oct  8 19:58 libopencryptoki.so.0 -> libopencryptoki.so.0.0.0
-rwxr-xr-x 1 root root 390688 Oct  8 19:58 libopencryptoki.so.0.0.0
lrwxrwxrwx 1 root root     15 Oct  8 19:58 methods -> /usr/local/sbin
lrwxrwxrwx 1 root root     18 Oct  8 19:58 PKCS11_API.so -> libopencryptoki.so
drwxr-xr-x 2 root root   4096 Oct  8 19:58 stdll

`

I also did the export of LD_LIBRARY_PATH before starting the daemon.

**Comment by ifranzki** [comment]
So it can't find its token DLLs. The token DLLs (shared libraries) are in `/usr/local/lib/opencryptoki/stdll/`. I don't see why it wont find them in your case.

**Comment by ifranzki** [comment]
Did you do an `ldconfig `after setting up the export LD_LIBRARY_PATH ?

**Comment by johughes99** [comment]
Many thanks.  That sorted it out. I will write it down - so I don't forget whats required to install and configure

I can see you now have good EC support.

I will start testing it now.
