### ISSUE TITLE
ckm_aes_wrap_format() should malloc instead of realloc

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#32]
ckm_aes_wrap_format() should call malloc to allocate memory with the new size. Zero out the new memory and then copy the old data into it. Then zero out the old data (since a key) and free it.

> // JML: Why for cca did we realloc with size=64? Bug?
> // When RSA key to wrap, data_len might be like 780 bytes.
> // So we just chopped off most of key.
> // This worked by fluke. For example, if data_len = 780,
> // then len1=780, len2=784. realloc to 64, but set data_len=784.
> // Noticed for this case, ptr and data point to same thing
> // after realloc.
> // So we effectively give encrypt same data pointer with
> // datalength of 784. So we encrypt freed memory.
> // Worked because 1) pointer to same memory, and freed memory
> // was still hanging around.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/103/

**Comment by p-steuer** [comment]
Fixed by 47c058cd4030f68b96a30a0768b65be5ef6b5e20 . Closing.
