### ISSUE TITLE
CKR_PIN_LOCKED on using pkcsconf

### ISSUE THREAD

**Issue by johughes99** [opencryptoki/opencryptoki#322]
Some of my tests has caused a PIN locked situation. Two questions.

How do i get out of this?  I had thought the following would work

`pkcsconf -I -c 3
Enter the SO PIN: 
Enter a unique token label: mttoken
Error initializing token: 0xA4 (CKR_PIN_LOCKED)
`

But it didn't.

The second question is how I can increase the number of logon attempts?  Is there any parameter in opencryptoki.conf I can set to change the default

**Comment by ifranzki** [comment]
So the SO pin is locked? Then you can't get out of this with just pkcsconf commands.
You will need to remove the files in the token directory.
In  `/usr/local/var/lib/opencryptoki/swtok/` remove the files `MK_SO`, `MK_USER`, `NVTOK.DAT`, and in `/usr/local/var/lib/opencryptoki/swtok/TOK_OBJ/` remove all files. This will obviously delete all token objects (if any).
Then you should be able to initialize the token freshly using `pkcsconf -I -c 3`, with the default SO pin. 

Regarding the login attempts: No there is no way. 
On a logon attempt with an invalid pin, the flag CKF_USER_PIN_COUNT_LOW is set. On the next login attempt still with an invalid pin, flag CKF_USER_PIN_FINAL_TRY is set, and on the 3rd login attempt again with an invalid pin, flag CKF_USER_PIN_LOCKED is set and the pin is locked. On each successful login attempt these flags are cleared.

**Comment by johughes99** [comment]
Yes  - the SO pin is locked. I had assumed that you nneeded to clear out some files - but a quick google on the subject didnt really result in some good instructions.

re PIN locked - that's a shame. In my tests I will just have to make sure I do a successfuly login to make sure Im not locked out.
