### ISSUE TITLE
Remove lock files

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#33]
At some point when exiting from stdll, spinlocks should be removed (in close file should be closed and unlinked).

Migrated from https://sourceforge.net/p/opencryptoki/bugs/101/

**Comment by p-steuer** [comment]
Looked at it and this seems just to be about unlinking the lock files, so propably cant considered being a bug.

**Comment by ifranzki** [comment]
Since we do not know when the last opencryptoki process terminates, we don't know when to remove those lock files. Possibly, pkcssslotd cold do this when terminating?
