### ISSUE TITLE
Investigate tpm/MK_USER and tpm/MK_SO

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#34]
In tpm_stdll/loadsave.c investigate why load_masterkey_so() creates MK_SO in In tpm directory and not tpm/<user>/ directory.
Same thing for load_masterkey_user() making MK_USER in tpm directory.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/100/

**Comment by ifranzki** [comment]
It is very likely that this one is fixed with commit https://github.com/opencryptoki/opencryptoki/commit/460e3af391cbec7d414d94df6295a0f6472e114b

**Comment by ifranzki** [comment]
I consider this as fixed with commit https://github.com/opencryptoki/opencryptoki/commit/460e3af391cbec7d414d94df6295a0f6472e114b
