### ISSUE TITLE
PKCS11 Initialization Error

### ISSUE THREAD

**Issue by heobu** [opencryptoki/opencryptoki#340]
Hello,

I have a device with TPM 1.2 and I have come across some difficulties trying to load the PKCS#11 libraries and initializing them.

I have installed opencryptoki and tried to use the sample code in the how-to documentation of this repo. But C_Initialize function fails and returns "0x6" which is i think defined as the CKR_FUNCTION_FAILED error.

After this I checked and saw that trousers (tcsd) service is running though it also mentions device driver not being loaded:
![service1](https://user-images.githubusercontent.com/22464721/98543760-fcba1800-22a3-11eb-8446-8d36bdff86bc.PNG)

I don't know if the device driver not being loaded is significant, but when i execute tpm_version, i also get this error:
![image](https://user-images.githubusercontent.com/22464721/98543912-3c80ff80-22a4-11eb-92b2-798b5d4802d7.png)

I also checked and i am running pkcsslotd service as well if that is relevant:
![image](https://user-images.githubusercontent.com/22464721/98543956-502c6600-22a4-11eb-944e-16e41d571522.png)

I do not know if there is a step missing in the installation of the library and its dependencies or what could cause such an issue.

Thank you for your time, have a nice day.

**Comment by heobu** [comment]
Also I updated LD_LIBRARY_PATH as mentioned in [this](https://github.com/opencryptoki/opencryptoki/issues/319) issue as well but that didn't help. I updated the path as mentioned and restarted pkcsslotd basically, but still get the same errors.

I also get the same kind of "Error initializing the PKCSS11 library: 0x6 (CKR_FUNCTION_FAILED)" error when i execute "pkcsconf -i" on the terminal.

**Comment by ifranzki** [comment]
Can you please turn on the trace and attach the trace output:

export OPENCRYPTOKI_TRACE_LEVEL=4

Trace files are in /var/log/opencryptoki/trace.<pid> (or in /usr/local/var/log/opencryptoki/trace.<pid> if you installed it via make install).

**Comment by heobu** [comment]
I have tried that but annoyingly no logs are being produced. I have installed it via make install.

**Comment by heobu** [comment]
I think there was some file permission related issue, also i enabled debug i don't know if that helped, but now i can see the trace files being created under /usr/local/var/log/opencryptoki/trace, but their content is empty.
