### ISSUE TITLE
TPM: SO PIN cannot be changed

### ISSUE THREAD

**Issue by grawity** [opencryptoki/opencryptoki#357]
With 3.15.1 or git, after initializing a brand new TPM token, trying to use `pkcsconf -P` or `pkcs11-tool --login-type so --change-pin` fails with:

```
error: PKCS11 function C_SetPIN failed: rv = CKR_FUNCTION_FAILED (0x6)
```

The following is logged in /var/log/opencryptoki/trace:

```
01/09/2021 01:28:17 37833 [usr/lib/tpm_stdll/tpm_openssl.c:128 tpmtok] DEVEL: Tried 5 times to generate a valid RSA key, failed.
```

The issue seems to be that usr/lib/tpm_stdll/tpm_openssl.c uses EVP_PKEY_CTX_new_id() which creates a keygen-only context, with no pkey attached to it (EVP_PKEY_keygen _does not_ assign ctx->pkey), and this means EVP_PKEY_check() cannot possibly succeed.

(I don't think such a check is required – if EVP_PKEY_keygen() succeeded, then the generated key is valid...)

**Comment by ifranzki** [comment]
Can you lease retest with the commit https://github.com/ifranzki/opencryptoki/commit/21b9572f3a925cca36e2dc2c76a7dd404b7b3bf3 from https://github.com/opencryptoki/opencryptoki/pull/360 ?

**Comment by grawity** [comment]
Thanks, tested; both SO and user PIN changes now succeed.
