### ISSUE TITLE
TPM: Unable to initialize or change user PIN on new token

### ISSUE THREAD

**Issue by grawity** [opencryptoki/opencryptoki#358]
In the TPM token, C_InitPIN() does nothing at all – according to the comment in token_specific_init_pin(), the actual initialization is done when the user logs in the first time, and the CKF_USER_PIN_INITIALIZED flag is only set after a regular PIN change.

But since commit e23beaab365d5b17ad40670ef8c3a7dfe29ff7e0, it is no longer possible for the user to log in if CKF_USER_PIN_INITIALIZED isn't already set, making it impossible to change the PIN... The result is that it is impossible to finish initialization of the token on version 3.15.1.

**Comment by ifranzki** [comment]
Can you lease retest with the commit https://github.com/ifranzki/opencryptoki/commit/1c60b64208c1c57ebd1e9f3d056a80add8769e5a from https://github.com/opencryptoki/opencryptoki/pull/360 ?

**Comment by grawity** [comment]
Tested; the user PIN change now happens successfully.
