### ISSUE TITLE
Error initializing the PKCS11 library: 0x2 (CKR_HOST_MEMORY)

### ISSUE THREAD

**Issue by kingaj12** [opencryptoki/opencryptoki#370]
Hi - I am installing the soft version of the opencryptoki in a docker container - but I am getting an error.  Here are the details

    # cat /etc/os-release 
    NAME="Ubuntu"
    VERSION="18.04.5 LTS (Bionic Beaver)"

    # openssl version
    OpenSSL 1.1.1  11 Sep 2018

    # pkcsconf -t
    Error initializing the PKCS11 library: 0x2 (CKR_HOST_MEMORY)

Also, I don't see the `/etc/opencryptoki/opencryptoki.conf` file.  Would that have something to do with the error?

Here's the Dockerfile

    FROM ubuntu:bionic

    RUN apt-get -qq update 

    RUN apt-get install -y \
	expect trousers libldap2-dev libtspi-dev wget

    RUN apt-get install -y \
	zip unzip

    RUN cd /tmp && wget https://github.com/opencryptoki/opencryptoki/archive/master.zip 

    RUN unzip /tmp/master.zip -d /tmp

    RUN groupadd pkcs11

    RUN apt-get -qq update && apt-get install -y \
	build-essential autoconf

    RUN apt-get install -y \
	libtool

    RUN apt-get install -y \
	flex bison

    RUN cd /tmp/opencryptoki-master && bash bootstrap.sh 

    RUN cd /tmp/opencryptoki-master && ./configure && make

    RUN cd /tmp/opencryptoki-master && make install 

    RUN ldconfig

**Comment by ifranzki** [comment]
> Also, I don't see the /etc/opencryptoki/opencryptoki.conf file. Would that have something to do with the error?

`make install` will install it to `/usr/local/`, so you won't find `opencryptoki.conf` in `/etc/opencryptoki/`, but in `/usr/local/etc/opencryptoki/`.

> Error initializing the PKCS11 library: 0x2 (CKR_HOST_MEMORY)

Did you start `pkcsslotd`? 
Opencryptoki uses unix sockets to communicate between the `pkcsslotd `and the applications using Opencryptoki. It also uses shared memory segments. You might have to do something in you container to expose these to the applications.

Are you running `pkcsslotd `and the application within the same container? Or are you running `pkcsslotd `in one container, and the application in another container? If so, then you need to make the socket and the shared memory available to the application container. This might be a tricky thing to get all this sorted out.

**Comment by kingaj12** [comment]
Ah - no I didn't start `pkcsslotd`.  Sorry for the newbie question.

Thanks for the information about the sockets.  In our design, the container hosts the HSM and does the signing, etc, through APIs.  But we have to plan for stopping and restarting.  In the designs with `opencryptoki` is there a best practice for recovering keys?

**Comment by kingaj12** [comment]
I'll move this question to the mailing list.
