### ISSUE TITLE
FIPS: Create internal crypto interfaces

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#38]
Create a set of internal crypto interfaces that can be plugged into an external provider, such as libgcrypt, openssl's libcrypto, or the new user-space kernel cryptoAPI. 

Update all tokens to call these internal crypto interfaces for their internal operation (not calls through the PKCS#11 API)s.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/76/

**Comment by p-steuer** [comment]
Commit https://github.com/opencryptoki/opencryptoki/commit/7144c8c1a2b200de301f989100765fc1e62d3ec6 replaced sha1 code by libcrypto sha1.

**Comment by ifranzki** [comment]
At leasts all token-internal crypto is now based on OpenSSL (libcrypto). So I guess we can consider this issue as solved now.

**Comment by p-steuer** [comment]
I agree this is done.
