### ISSUE TITLE
FIPS: Convert object storage format to use FIPS algorithms

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#39]
Currently MD5 and SHA1 hashes are used as part of the object storage format, update them to use FIPS certifiable algorithms.

Design a version system so that it can be detected whether a data store is 1 format vs. another.

Refuse to enter FIPS mode for a specific token until its data store has been converted.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/77/

**Comment by ifranzki** [comment]
This one should be solved now with 3.12.

**Comment by p-steuer** [comment]
I agree this is solved mostly, up to the "Refuse to enter FIPS mode for a specific token until its data store has been converted." thing.

But since there are probably more things todo for real fips compliance ill close this one. We can opeen a new one when we know what alse is required for fips.
