### ISSUE TITLE
opencryptoki 3.16 : failed to init token

### ISSUE THREAD

**Issue by lhuynh-cs** [opencryptoki/opencryptoki#393]
Token initialization worked well with 3.13 but failed with 3.16.
In the log : 
[usr/lib/common/shared_memory.c:264 swtok] ERROR: Error shared memory "xxx" exists and does not match the expected size

Thanks for help

**Comment by ifranzki** [comment]
Simply remove the existing shared memory segments under `/dev/shm` that belong to Opencryptoki. Make sure that no Opencryptoki process is currently active, and that the pkcsslotd is stopped when you remove them. 

After removing them, just start pkcsslotd again and your applications should be able to start up just fine. This will also recreate the shared memory segments as needed.
