### ISSUE TITLE
FIPS: Change the USER/SO PIN's key derivation algorithm

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#40]
Currently MD5 and SHA1 are used to derive a key used to decrypt the master key. Also, IV's are hard-coded in the source, which reduces security to the derivation of the key alone.

Change the algorithm to generate enough random data to provide the IV and key instead of hard-coding the IV

One algorithm possibility is the TLS 1.2 master key derivation process.

Migrated from https://sourceforge.net/p/opencryptoki/bugs/78/

**Comment by ifranzki** [comment]
Isn't this now fixed with 3.13?

**Comment by p-steuer** [comment]
your right.
