### ISSUE TITLE
p11sak: Support the PKCS #11 URI Scheme (RFC 7512)

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#41]
Consider registering with NSS's pkcs11.txt file, as outlined in [1].  This may ease setup in some cases.  A further enhancement would be to add code to parse the parameters options, which come in through C_Initialize when NSS inits a pkcs11 module.

[1] http://codeverge.com/mozilla.dev.tech.crypto/using-p11-kit-standard-registry-for-l/1510493

Migrated from https://sourceforge.net/p/opencryptoki/bugs/83/

**Comment by p-steuer** [comment]
See also https://tools.ietf.org/html/rfc7512 .

**Comment by ifranzki** [comment]
p11sak should have an option to list URIs of the key (any maybe tokens).
