### ISSUE TITLE
pkcstok_migrate: asks to stop pkcsslotd which is already stopped

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#420]
I am able to reproduce the issue in about 1 out of 20 runs, this is obviously some race condition.

echo y | pkcstok_migrate -s 3 -d /var/lib/opencryptoki/swtok -c /etc/opencryptoki/ -p 76543210 -u 01234567

pkcstok_migrate:
Summary of input parameters:
  datastore = /var/lib/opencryptoki/swtok 
  confdir = /etc/opencryptoki 
  slot ID = 3
  user PIN specified
  SO PIN specified

pkcstok_migrate finished with warnings/errors.
pkcstok_migrate: fopen(/proc/1479737/cmdline) failed, errno=No such file or directory
pkcstok_migrate: Please stop pkcsslotd before running this utility.

I am not able to tell to which process the process ID 1479737 belongs to but I suspect it could be the 'echo y' process itself. Anyway, looking at the source https://github.com/opencryptoki/opencryptoki/blob/master/usr/sbin/pkcstok_migrate/pkcstok_migrate.c#L2496
it seems it cannot deal with a situation where the respective process is not running any more.
Unless a different method of checking if pkcsslotd is running (systemctl, PID file) can be used, the code should be at least able to handle a situation when the required file does not exist, this is in fact quite expected for /proc content.

**Comment by ifranzki** [comment]
Thanks for reporting this. Yes, the detection logic is way to strict, and can't handle situations here processes terminate while we are iterating over the processes.

I have added a fix for this to my already open pull request https://github.com/opencryptoki/opencryptoki/pull/419 that already contains another fix for pkcstok_migrate.

Please note that there is another fix for pkcstok_migrate already available: https://github.com/opencryptoki/opencryptoki/commit/5824364d995e5d2418f885ee57e377e11d1b3302 "pkcstok_migrate: Quote strings with spaces in opencryptoki.conf"

**Comment by ngothan** [comment]
Hi Ingo,
thank you so much for quick fix. The patch looks good. I will pass the patch to our QA for testing.
