### ISSUE TITLE
p11sak: Extend tool to cover Generic-Secret, DH and DSA key types

### ISSUE THREAD

**Issue by chrisRund** [opencryptoki/opencryptoki#441]
Currently the p11sak tool does not support the generation, display, and removal of DSA type objects.
The only token supporting DSA is the EP11 token, such that the p11sak tool should also print an informational message if a user tries to create DSA objects on a token different than the EP11 token.

Currently the p11sak tool supports des, 3des, aes, rsa, and ec type objects.

Please integrate support for creating, displaying, and deleting DSA objects into the p11sak tool
Thanks.

**Comment by ifranzki** [comment]
Maybe support for DH (instead of DSA) is of more interest ?

**Comment by ifranzki** [comment]
Also add support for generating Generic-Secret keys (HMAC keys)

**Comment by ifranzki** [comment]
Support for other key types is now available with commit https://github.com/opencryptoki/opencryptoki/commit/e52f78503e201153bd37e8001aa68998dce5cbc7 and following.
