### ISSUE TITLE
usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock 

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#445]
Description of problem:

The below error is observed when the user executes the command "p11-kit list-modules" and iopencryptoki is installed
```
- /var/log/messages

  ----------------------------------------------------------------------------
Aug 20 11:06:45 prereserve-1mt p11-kit[5736]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Aug 20 11:09:46 prereserve-1mt p11-kit[5748]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Aug 20 11:28:03 prereserve-1mt p11-kit[6644]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Aug 20 11:28:12 prereserve-1mt p11-kit[6647]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Aug 20 11:30:59 prereserve-1mt p11-kit[7471]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
Aug 20 11:38:58 prereserve-1mt p11-kit[7485]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock
  ----------------------------------------------------------------------------
```
Simple reproducer:
1. p11-kit list-modules
   does not produce the log in the journal
2. dnf install -y opencryptoki; p11-kit list-modules
   produces the log in the journal: p11-kit[5645]: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock

Reproduced with opencryptoki-3.15.1-5.el8.x86_64 and latest 3.16
Not reproduced with opencryptoki-3.14.0-5.el8.x86_64

**Comment by ngothan** [comment]
it seems the error was caused by /usr/share/p11-kit/modules/opencryptoki.module file  that allows p11-kit to use opencryptoki.

```
-  /usr/share/p11-kit/modules/opencryptoki.module
----------------------------------------------------------------------------
# This file describes how to load the opensc module
# See: http://p11-glue.freedesktop.org/doc/p11-kit/config.html

# This is a relative path, which means it will be loaded from
# the p11-kit default path which is usually $(libdir)/pkcs11.
# Doing it this way allows for packagers to package opensc for
# 32-bit and 64-bit and make them parallel installable
module: libopencryptoki.so
----------------------------------------------------------------------------
```
the error disappears after removing that file.

**Comment by ifranzki** [comment]
I can't tell how that error relates to the /usr/share/p11-kit/modules/opencryptoki.module.... 
Message `Could not open /run/lock/opencryptoki/LCK..APIlock` is issued when opencryptoki fails to open its lock file:

```
CK_RV CreateProcLock(void)
{
    if (xplfd == -1) {

        /* The slot mgr daemon should have already created lock,
         * so just open it so we can get a lock...
         */
        xplfd = open(OCK_API_LOCK_FILE, O_RDONLY);

        if (xplfd == -1) {
            OCK_SYSLOG(LOG_ERR, "Could not open %s\n", OCK_API_LOCK_FILE);
            return CKR_FUNCTION_FAILED;
        }
    }

    return CKR_OK;
}
```

**Comment by ngothan** [comment]
@ifranzki ,i found out that this error is caused by not having the pkcsslotd daemon running.  Do you think it is useful  or maybe any trouble to make opencryptoki module usable for p11-kit?

**Comment by ifranzki** [comment]
Its certainly useful to make opencryptoki usable for p11-kit. 

@p-steuer what do you think?

**Comment by p-steuer** [comment]
I already used openCryptoki with p11-kit, see : https://www.ibm.com/docs/en/linux-on-systems?topic=service-server-side-setup

Are you aware of something that is missing to enable openCryptoki for p11-kit ?

**Comment by ifranzki** [comment]
@ngothan any news on this?

**Comment by ngothan** [comment]
@ifranzki , to allows p11-kit to use opencryptoki we need to add the config file "opencryptoki.module" which should be installed under /usr/share/p11-kit/modules/ and  for this purpose it requires that pkcsslotd is already started before, otherwise you get the error message "PA: usr/lib/api/apiutil.c Could not open /run/lock/opencryptoki/LCK..APIlock"
It means pkcsslotd service should be enable by default.

opencryptoki.module file:
```
# This file describes how to load the opensc module
# See: http://p11-glue.freedesktop.org/doc/p11-kit/config.html

# This is a relative path, which means it will be loaded from
# the p11-kit default path which is usually $(libdir)/pkcs11.
# Doing it this way allows for packagers to package opensc for
# 32-bit and 64-bit and make them parallel installable
module: libopencryptoki.so
```

**Comment by ifranzki** [comment]
> pkcsslotd service should be enable by default

I doubt that it is a good idea to enable the pkcsslotd service by default. Usually opencryptoki requires some configuration (defining the desired tokens in the opencryptoki config files, etc) before the pkcsslotd can be started. So I would not start it by default. it should be at the admins decision if and when to start the pkcsslotd.

**Comment by ngothan** [comment]
I agree that it is risky to enable the pkcsslotd service by default. It can cause problems in case of bad configuration. I am closing it.
