### ISSUE TITLE
A locking bug in the method C_Initialize

### ISSUE THREAD

**Issue by ryancaicse** [opencryptoki/opencryptoki#493]
The global lock `GlobMutex` is not correctly released when `rc != CKR_OK`, should it be a bug?
https://github.com/opencryptoki/opencryptoki/blob/a67dfb19494b91de64683eb1cefe30c55b253ee2/usr/lib/api/api_interface.c#L2864-L2875

**Comment by ifranzki** [comment]
You are right. Should go to `done` instead of return. 
Will make a fix and open a PR for this.
