### ISSUE TITLE
Log failure when CKA_PUBLIC_KEY_INFO is rejected

### ISSUE THREAD

**Issue by minfrin** [opencryptoki/opencryptoki#495]
As per https://github.com/opencryptoki/opencryptoki/commit/7d5188407d7c146485fd2703fb578e5e966abbc7 attempts to set CKA_PUBLIC_KEY_INFO on private keys is rejected with CKR_ATTRIBUTE_TYPE_INVALID, alas nothing is logged when this happens.

A log line needs to be added before this line so the end user is alerted to why the import failed.

https://github.com/opencryptoki/opencryptoki/blob/7d5188407d7c146485fd2703fb578e5e966abbc7/usr/lib/common/key.c#L1258

**Comment by ifranzki** [comment]
Yes it would probably be helpful to issue a trace message in this case, too.

**Comment by minfrin** [comment]
Thank you for this.
