### ISSUE TITLE
p11sak key-generate: support custom attributes

### ISSUE THREAD

**Issue by jschmidb** [opencryptoki/opencryptoki#500]
We are now able to display custom/vendor attributes via the config file. But p11sak does not support specifying such attrs at key-generation. We could e.g. provide a way to let the user introduce a new char for a custom attr in the config file, such as:
```
attribute {
   name = CKA_IBM_PROTKEY_EXTRACTABLE
   letter = P
   id = 0x8001000c
   type = CK_BBOOL
}
```
and then allow to specify this letter in the --attr parm. 
`# p11sak generate-key aes 128 --attr P ... `
Or support new dynamic parms on the basis of attribute names, like:
`# p11sak generate-key aes 128 --CKA_IBM_PROTKEY_EXTRACTABLE=1 ... `
OK, there are many ways ...

**Comment by ifranzki** [comment]
Known boolean vendor specific attributes such as CKA_IBM_PROTKEY_EXTRACTABLE can now be specified with the current version of p11sak using letter 'K' (sorry, 'P' was already used for CKA_PRIVATE).
