### ISSUE TITLE
pkcsslot -t freeze when run by user not in pkcs11 group

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#507]
Running pkcsconf -t ( opencryptoki-3.17.0) by user not in pkcs11 group freeze the following error is shown:
```
Error initializing the PKCS11 library: 0x6 (CKR_FUNCTION_FAILED)
Note: all non-root users that require access to PKCS#11 tokens using opencryptoki must be assigned to the pkcs11 group to be able to communicate with the pkcsslotd daemon.
```
At this moment the process is stuck.  This Problem is not present when user is in pkcs11 group and it is also not present in opencryptoki-3.15.1

**Comment by ifranzki** [comment]
I can reproduce this issue.

It hangs at api_interface.c `C_Finalize()` at line 1651 when it tries to get the global mutex. This mutex seems to be still held.

Looking at `C_Initialize()`, it first locks this global mutex, then checks the user and groups, and if this fails, it goes to label `done:`. At `done`, it unlocks the global mutex.....

```
done:
    pthread_mutex_unlock(&GlobMutex);

    return rc;
}                               // end of C_Initialize
```
However, running this in the debugger shows that it never really does the `pthread_mutex_unlock()` but returns right away. For whatever reason it skips the `pthread_mutex_unlock()`, and thus the mutex is still held.
