### ISSUE TITLE
pthread_atfork should not be used with library that should be dlopened/dlclosed

### ISSUE THREAD

**Issue by juergenchrist** [opencryptoki/opencryptoki#534]
Consider this sequence:
```
dlopen(opencryptoki)
C_Initialize()
C_Finalize()
dlclose(opencryptoki)
fork()
```
Then, since `C_Initialize` calls `pthread_atfork` for register at-fork handlers (code within opencryptoki), the fork after the `dlclose` will jump to unmapped adresses and execute potentially malicious code placed there (or simply crash if no code is placed there).  As a quick fix we should at least document that opencryptoki does not completely unregister (since that is not possible - there is no `pthread_deleteatforkhandler`) and therefore nobody should fork after unloading opencryptoki.  In the long run I think we need a different solution to the problem the atfork handler is supposed to solve.

**Comment by ifranzki** [comment]
Did you actually run into this situation in a test? 
I had the impression that dlclose is smart enough to unregister any atfork handlers that the to be unloaded library has registered.... I might be wrong though.

**Comment by ifranzki** [comment]
Found this in glibc/stdlib/cxa_finalize.c in function `__cxa_finalize` at the very end:

```
  /* Remove the registered fork handlers.  We do not have to
     unregister anything if the program is going to terminate anyway.  */
  if (d != NULL)
    UNREGISTER_ATFORK (d);
```

This sounds as if it would remove the fork handlers of that library at the library's destructor.
And this should then prevent the unloaded libraries' fork handler to be called at the next fork(). 

What do you think?

**Comment by juergenchrist** [comment]
That would work, but is it standardized or only a glibc extension?

**Comment by ifranzki** [comment]
I consider this as resolved for now. 
If we ever encounter a real-world situation where one runs Opencrptoki with a non-glibc that behaves different in terms of atfork handlers and library destructors, we might consider this further.
