### ISSUE TITLE
multiple defects found by covscan in opencryptoki-3.18.0

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#562]
there are multiple defects in opencryptoki-3.18.0 found by covscan. The list of defects is large. I attach the covscan-result.log file.

[opencryptoki-3.18.0-covscan.log](https://github.com/opencryptoki/opencryptoki/files/8872836/opencryptoki-3.18.0-covscan.log)

It looks like there are a lot of detects which are false positives.

Thanks

**Comment by ifranzki** [comment]
Thanks for reporting this. I will go over the list as time permits, but this will take a while, I guess.
