### ISSUE TITLE
Add NSS 3.30 new vendor specific attribute

### ISSUE THREAD

**Issue by dodys** [opencryptoki/opencryptoki#57]
NSS 3.30 introduces a new vendor specific PKCS #11 attribute CKA_NSS_MOZILLA_CA_POLICY:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/NSS_3.30_release_notes

We should add this attribute in the PKCS #11 attribute lists (macros). 
For testing we can use Apache with mod_nss and openCryptoki.

**Comment by dvelarde** [comment]
Merged patch submitted by ifranzki that fixes this issue.
