### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by kloczek** [opencryptoki/opencryptoki#599]
https://github.com/opencryptoki/opencryptoki/compare/v3.18.0...master shows +100 commits since last release.
I think that it would be good to flush all that anf tag new version 😋

**Comment by ifranzki** [comment]
Stay tuned, there will be a 3.19.0 in the next few weeks... :-)

**Comment by ifranzki** [comment]
See https://github.com/opencryptoki/opencryptoki/releases/tag/v3.19.0

**Comment by kloczek** [comment]
Just tested new version and it builds correctly.
Thank you 👍
