### ISSUE TITLE
second instance

### ISSUE THREAD

**Issue by jkr1987** [opencryptoki/opencryptoki#673]
hello,
I'm looking for a path to install two instances of opencryptoki library.
I would like be able to load  two instances of opencryptoki library in the same application ("one after the other" or in "same time").

the goal is to simulate two different SW-HSM and not just using two slot.

anyone have an idea how to do it?
thanks.

**Comment by ifranzki** [comment]
That's not possible. You can run pkcsslotd only once , thus only one instance of OpenCryptoki can run at at time. 

What would be the difference of running 2 instances of OpenCryptoki, versus having just 2 slots of the same token in one OpenCryptoki instance?

**Comment by ifranzki** [comment]
If you want to use two different PKCS#11 implementations in one application, e.g. a token from OpenCryptoki and another token from SoftHSM (https://github.com/opendnssec/SoftHSMv2), then you should give `p11-kit` a try, see https://p11-glue.github.io/p11-glue/p11-kit.html. With p11-kit you can define several so called modules that are all loaded by p11-kit and offered to an application as a single PKCS#11 library. It kind of virtualizes all the slots from the various modules and provides each of them under a uniqe slot id to the application.

**Comment by jkr1987** [comment]
thanks you for all your answers ! 
`What would be the difference of running 2 instances of OpenCryptoki, versus having just 2 slots of the same token in one OpenCryptoki instance? 
I'm agree but i need that to simulate two HSM.
