### ISSUE TITLE
init_slotinfo() is redundant

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#7]
pkcsslotd reads opencryptoki.conf and gets the manufacturer, description, firmware version and hardware version for a slot. This info is then entered into a slot entry and the slot itself becomes part of an array of slots. The array is stored in pkcsslotd's shared memory. Since the API access this shared memory, this slotinfo is returned in calls to C_GetSlotInfo().

BUT, in utility.c, there is an init_slotinfo() which declares a slot for the token and puts the manufacturer, etc... info into it using the info defined in the token.

This is redundant! Why does the token also create a slot entry and use different info from what pkcsslotd does. There should be one method to acquire slot info and both pkcsslotd and token should use it.

One idea is to pass the slotinfo from pkcsslotd in the SC_XXX api to the token and let it use that.

OR

if it is better to keep init_slotinfo() in the token, then a token specific getslotinfo and token specific getslotlist are needed.

Either way, this is redundant and needs to be examined and fixed.

This issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/125/

**Comment by ifranzki** [comment]
I think this is correct as it is. The slot daemon provides SLOT information, while the token provides TOKEN information. SLOT is a synonym for the smart card reader, while the token is a synonym for the smart card itself. Both can (and most likely do) have different information (i.e. manufacturer, description, firmware version and hardware version).

**Comment by ifranzki** [comment]
I consider this as working as designed. Closing.
