### ISSUE TITLE
Not able to run test cases

### ISSUE THREAD

**Issue by shreenivasboodi** [opencryptoki/opencryptoki#759]
Hi @ifranzki,

I have built and installed opencryptoki library. Currently I am trying to build it, getting below errors. Please check and let me know whether I am running test case properly or not. I am using opencryptoki/testcases/ock_tests.sh.in file for executing test cases

shreenivas@LAPTOP-46AHQ1S1:~/aeva/opencryptoki/testcases$ sudo ./ock_tests.sh -s 3 -f login/
632450
633309
700367
********** Testing Slot 3 **********
Software Token type detected
***** Will run the following tests for slot 3: login_flags.c
login.c
login_test.sh
init_tok.c
set_pin.c
README
init_pin.c
digest_init.c
login.mk
** Now executing 'login_flags.c'
./ock_tests.sh: line 249: login_flags.c: command not found
ERROR: Testcase login_flags.c failed to execute, rc: 127
** Now executing 'login.c'
./ock_tests.sh: line 249: login.c: command not found
ERROR: Testcase login.c failed to execute, rc: 127
** Now executing 'login_test.sh'
./ock_tests.sh: line 249: login_test.sh: command not found
ERROR: Testcase login_test.sh failed to execute, rc: 127
** Now executing 'init_tok.c'
./ock_tests.sh: line 249: init_tok.c: command not found
ERROR: Testcase init_tok.c failed to execute, rc: 127
** Now executing 'set_pin.c'
./ock_tests.sh: line 249: set_pin.c: command not found
ERROR: Testcase set_pin.c failed to execute, rc: 127
** Now executing 'README'
./ock_tests.sh: line 249: README: command not found
ERROR: Testcase README failed to execute, rc: 127
** Now executing 'init_pin.c'
./ock_tests.sh: line 249: init_pin.c: command not found
ERROR: Testcase init_pin.c failed to execute, rc: 127
** Now executing 'digest_init.c'
./ock_tests.sh: line 249: digest_init.c: command not found
ERROR: Testcase digest_init.c failed to execute, rc: 127
** Now executing 'login.mk'
./ock_tests.sh: line 249: login.mk: command not found
ERROR: Testcase login.mk failed to execute, rc: 127
********** Finished Testing Slot 3 with RC=127 **********
********** At least one slot finished with error **********
ERROR: Testcase login_flags.c failed to execute for slot 3, rc: 127
ERROR: Testcase login.c failed to execute for slot 3, rc: 127
ERROR: Testcase login_test.sh failed to execute for slot 3, rc: 127
ERROR: Testcase init_tok.c failed to execute for slot 3, rc: 127
ERROR: Testcase set_pin.c failed to execute for slot 3, rc: 127
ERROR: Testcase README failed to execute for slot 3, rc: 127
ERROR: Testcase init_pin.c failed to execute for slot 3, rc: 127
ERROR: Testcase digest_init.c failed to execute for slot 3, rc: 127
ERROR: Testcase login.mk failed to execute for slot 3, rc: 127

**Comment by ifranzki** [comment]
You pass `-f login/` to `ock_tests.sh` probably to run all the test in the `testcases/login/` directory. 
Unfortunately `ock_tests.sh` is a bit stupid and tries to run all files available in that directory. Obviously the `.c` files as well as others are not executable and thus fail tu run. 

Instead you should pass the names of the test executables via `-f` option. 
Or just run the test manually like ./testcases/login/<test-executable>.

Please note that some test in the login directory are destructive, they may corrupt the tokens/pins etc. So that's why those tests are not included in the default list of tests to run with `ock_tests.sh`.

**Comment by ifranzki** [comment]
You need to configure it with `--enable-testcases`, then it will build the testcases as well during `make`.

**Comment by shreenivasboodi** [comment]
Now I am able to run test cases. Thank you very much for your help.
