### ISSUE TITLE
opencryptoki compatibility on QNX

### ISSUE THREAD

**Issue by shreenivasboodi** [opencryptoki/opencryptoki#762]
@ifranzki I want to build opencryptoki on QNX, so want to know whether it is compatible on QNX or anyone tried building it on QNX?

**Comment by ifranzki** [comment]
Currently opencryptoki only supports Linux (on different architectures though). 

PR https://github.com/opencryptoki/opencryptoki/pull/749 attempts to add support for AIX, but I guess this won't help much in supporting QNX.
