### ISSUE TITLE
How to remove installed opencryptoki files

### ISSUE THREAD

**Issue by shreenivasboodi** [opencryptoki/opencryptoki#765]
@ifranzki I have installed opencryptoki in /usr/local directory, want to install it in /usr directory. Before installing it in /usr directory, I want to remove it from /usr/local directory. Do you know how to remove, Is there any command available? or I need to remove on my own using command **rm -rf**.

**Comment by ifranzki** [comment]
Normally, if you have installed it via `make install` you can uninmstall it via `make uninstall`. This should remove all files that have been installed during `make install`.
