### ISSUE TITLE
opencryptoki-3.24.0 build fails on i686 due incompatible pointer types 

### ISSUE THREAD

**Issue by ngothan** [opencryptoki/opencryptoki#809]
build fails on i686 due incompatible pointer types in Fedora Rawhide with gcc-14.2.1-2.fc42.i686, please see 
https://kojipkgs.fedoraproject.org//work/tasks/1002/123301002/build.log for the full logs

...

libtool: compile:  gcc -DPACKAGE_NAME=\"openCryptoki\" -DPACKAGE_TARNAME=\"opencryptoki\" -DPACKAGE_VERSION=\"3.24\" "-DPACKAGE_STRING=\"openCryptoki 3.24\"" -DPACKAGE_BUGREPORT=\"https://github.com/opencryptoki/opencryptoki/issues\" -DPACKAGE_URL=\"https://github.com/opencryptoki/opencryptoki\" -DPACKAGE=\"opencryptoki\" -DVERSION=\"3.24\" -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYS_PARAM_H=1 -DSTDC_HEADERS=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE__BOOL=1 -DHAVE_ARPA_INET_H=1 -DHAVE_FCNTL_H=1 -DHAVE_LIBINTL_H=1 -DHAVE_LIMITS_H=1 -DHAVE_LOCALE_H=1 -DHAVE_MALLOC_H=1 -DHAVE_NL_TYPES_H=1 -DHAVE_STDDEF_H=1 -DHAVE_SYS_FILE_H=1 -DHAVE_SYS_SOCKET_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_SYSLOG_H=1 -DHAVE_TERMIOS_H=1 -Drestrict=__restrict__ -DHAVE_ALLOCA_H=1 -DHAVE_ALLOCA=1 -DHAVE_CHOWN=1 -DHAVE_FORK=1 -DHAVE_VFORK=1 -DHAVE_ALARM=1 -DHAVE_GETPAGESIZE=1 -DHAVE_WORKING_VFORK=1 -DHAVE_WORKING_FORK=1 -DHAVE_MMAP=1 -DHAVE_DECL_STRERROR_R=1 -DHAVE_STRERROR_R=1 -DHAVE_ATEXIT=1 -DHAVE_FTRUNCATE=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_LOCALTIME_R=1 -DHAVE_MEMCHR=1 -DHAVE_MEMMOVE=1 -DHAVE_MEMSET=1 -DHAVE_MKDIR=1 -DHAVE_MUNMAP=1 -DHAVE_REGCOMP=1 -DHAVE_SELECT=1 -DHAVE_SOCKET=1 -DHAVE_STRCHR=1 -DHAVE_STRCSPN=1 -DHAVE_STRDUP=1 -DHAVE_STRERROR=1 -DHAVE_STRNCASECMP=1 -DHAVE_STRRCHR=1 -DHAVE_STRSTR=1 -DHAVE_STRTOL=1 -DHAVE_STRTOUL=1 -DYYTEXT_POINTER=1 -DNO_PKEY=1 -D_GNU_SOURCE=1 -DHAVE_LBER_H=1 -DHAVE_LDAP_H=1 -DNOMD2=1 -DPKCS64=1 -D_XOPEN_SOURCE=600 -DPKCSSLOTD_USER=\"pkcsslotd\" -DPKCS_GROUP=\"pkcs11\" -I. -DDEV -D_THREAD_SAFE -DSHALLOW=0 -DSWTOK=1 -DLITE=0 -DNOMD2 -DNODSA -DNORIPE -fPIC -I./usr/lib/soft_stdll -DTOK_NEW_DATA_STORE=0x0003000c -I./usr/lib/common -I./usr/include -DSTDLL_NAME=\"swtok\" -I./usr/lib/api -I./usr/lib/api -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -m32 -O2 -g3 -DHAVE_ALT_FIX_FOR_CVE2022_4304 -Wall -Wextra -std=c99 -Werror=implicit-int -Werror=implicit-function-declaration -Werror=int-conversion -Werror=strict-prototypes -Werror=old-style-definition -pedantic -DCONFIG_PATH=\"/var/lib/opencryptoki\" -DSBIN_PATH=\"/usr/sbin\" -DLIB_PATH=\"/usr/lib\" -DRUN_PATH=\"/run\" -DLOCKDIR_PATH=\"/var/lock/opencryptoki\" -DOCK_CONFDIR=\"/etc/opencryptoki\" -DOCK_LOGDIR=\"/var/log/opencryptoki\" -c usr/lib/common/mech_openssl.c  -fPIC -DPIC -o usr/lib/common/.libs/opencryptoki_stdll_libpkcs11_sw_la-mech_openssl.o
make[1]: Leaving directory '/builddir/build/BUILD/opencryptoki-3.24.0-build/opencryptoki-3.24.0'
usr/lib/common/mech_openssl.c: In function 'openssl_specific_hmac':
usr/lib/common/mech_openssl.c:4751:36: error: passing argument 2 of 'get_sha_size' from incompatible pointer type [-Wincompatible-pointer-types]
 4751 |     rc = get_sha_size(digest_mech, &mac_len);
      |                                    ^~~~~~~~
      |                                    |
      |                                    size_t * {aka unsigned int *}
In file included from usr/lib/common/mech_openssl.c:22:
usr/lib/common/h_extern.h:475:45: note: expected 'CK_ULONG *' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
  475 | CK_RV get_sha_size(CK_ULONG mech, CK_ULONG *hsize);
      |                                   ~~~~~~~~~~^~~~~
usr/lib/common/mech_openssl.c: In function 'openssl_specific_hmac_final':
usr/lib/common/mech_openssl.c:4851:36: error: passing argument 2 of 'get_sha_size' from incompatible pointer type [-Wincompatible-pointer-types]
 4851 |     rc = get_sha_size(digest_mech, &mac_len);
      |                                    ^~~~~~~~
      |                                    |
      |                                    size_t * {aka unsigned int *}
usr/lib/common/h_extern.h:475:45: note: expected 'CK_ULONG *' {aka 'long unsigned int *'} but argument is of type 'size_t *' {aka 'unsigned int *'}
  475 | CK_RV get_sha_size(CK_ULONG mech, CK_ULONG *hsize);
      |                                   ~~~~~~~~~~^~~~~
make[1]: *** [Makefile:9241: usr/lib/common/opencryptoki_stdll_libpkcs11_sw_la-mech_openssl.lo] Error 1

**Comment by ifranzki** [comment]
Hi @ngothan, please check if the fix in https://github.com/opencryptoki/opencryptoki/pull/810 does solve the problem for you.

**Comment by ngothan** [comment]
Hi @ifranzki, I confirm that opencryptoki-3.24.0 is now built with the fix without any problems.
Thanks!
