### ISSUE TITLE
CKA_LOCAL not set when generating keypair

### ISSUE THREAD

**Issue by pvital** [opencryptoki/opencryptoki#9]
Most mech_xxx.c key generating routines set CKA_LOCAL when generating a key. But this seems to be missing for RSA.

This issue was migrated from https://sourceforge.net/p/opencryptoki/bugs/139/

**Comment by hfreude** [comment]
Checked this in the ock code. It is true - some mech_xxx.c files set the CKA_LOCAL attribute, others don't.
At least the ika token does on RSA keypair generation add the CKA_LOCAL attribute but other tokens don't (CCA, softtoken). According to the standard this attribute should always be there ...
Needs investigation and fix.

**Comment by ifranzki** [comment]
CKA_LOCAL is set/added with a value of FALSE in **key_object_set_default_attributes()** in key.c. As far as I can tell, key_object_set_default_attributes() is called from within object_mgr_create_skel() whenever a key object (secret, private and public key) is created, either by means of C_CreateObejct, but also by means of C_GenerateKey(Pair). 

If CKA_LOCAL should be TRUE for RSA keygen's, then I would suggest to add this to mech_rsa.c function ckm_rsa_key_pair_gen() similar as other mech_xxx.c do this (using template_update_attribute()). I would not require each token to do this, but rather let common code handle this correctly.

**Comment by p-steuer** [comment]
As far as i know, this has been fixed by PR https://github.com/opencryptoki/opencryptoki/pull/203 . Please re-open if this is not the case.
